version: "3.5"

services:
boilerplate-adonisjs:
  container_name: boilerplate-adonisjs
  # image: colocar image
  restart: always
  ports:
   - "3333:3333"
  networks:
   - boilerplate-adonisjs-network
  env_file:
    - stack.env
networks:
  boilerplate-adonisjs-network:
   name: boilerplate-adonisjs-network
   driver: bridge


