version: "3.5"
services:
  boilerplate-adonisjs:
    container_name: boilerplate-adonisjs
    build:
     context: .
     dockerfile: Dockerfile.dev
    restart: always
    ports:
    - "3333:3333"
    volumes:
     - .:/app/boilerplate-adonisjs
     - node-modules-boilerplate-adonisjs:/app/boilerplate-adonisjs/node_modules
    networks:
      - boilerplate-adonisjs-network
      - postgres-network
volumes:
  node-modules-boilerplate-adonisjs:
   name: node-modules-boilerplate-adonisjs
networks:
  boilerplate-adonisjs-network:
   name: boilerplate-adonisjs-network
   driver: bridge
  postgres-network:
    name: postgres-network
    external: true

