FROM node:16.17-alpine


WORKDIR /app/default-project-adonis


COPY package*.json .

RUN npm install

RUN node ace generate:manifest  && node ace build --production


RUN cd build && npm ci --production

RUN cat env-production >> .env

COPY ./run-prod.sh /tmp
RUN chmod +x run-prod.sh

ENTRYPOINT ["sh", "/tmp/run-prod.sh"]
