export type Permissions =
  | 'createPermission'
  | 'deletePermission'
  | 'updatePermission'
  | 'viewPermission'
  | 'createRole'
  | 'updateRole'
  | 'viewRole'
  | 'deleteRole'
  | 'syncRolesPermissions'