name: CI
on:
  pull_request:
    branches:
      - production
      - development
jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: Boilerplate-test
          POSTGRES_PASSWORD: XWkIaeExxDmRwdm
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Checking types
        run: node ace type-check
      - name: Format code
        run: npm run format
      - name: Verify errors eslint
        run: npm run lint
      - name: Running tests
        run: node ace test
